# Generated by Django 5.2.8 on 2025-11-30 22:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(help_text='Must end with @technikum-wien.at', max_length=254, unique=True)),
                ('study_program', models.CharField(max_length=200)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of interests, max 5', size=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
